@node Credits, , To Do List, Top
@appendix Credits

This section is dedicated to those people who contributed in some way to
xmlwrapp. If we have forgotten you, please forgive us and drop the
current maintainer a note.

@menu
* Original Author::
* Maintainers::
* Contributers::
* Other Software::
@end menu

@node Original Author, Maintainers, , Credits
@section Original Author

The following person is the original author and maintainer through
version 0.5.0:

@itemize

@item
@uref{http://pmade.org/cgi-bin/people.cgi?p=pj,Peter Jones}.
@end itemize

@node Maintainers, Contributers, Original Author, Credits
@section Maintainers

The following person currently maintains xmlwrapp.

@itemize

@item
Tom Browder @email{tbrowder2@@users.sourceforge.net}
@end itemize

@node Contributers, Other Software, Maintainers, Credits
@section Contributers

The following people have made contributions to xmlwrapp.

@itemize

@item
Greg Chicares

@item
Daniel Evison

@item
Frank Grimm

@item
Gary Passero

@item
Karl Berry, maintainer of the GNU Texinfo system
@end itemize

@node Other Software, , Contributers, Credits
@section Other Software

We would also like to thank the following software projects.

@itemize

@item
@uref{http://xmlsoft.org/,libxml2} -
Thanks for the great XML parser library and the use of the MIT License and not the GPL.

@item
@uref{http://gcc.gnu.org/,GNU Compiler Collection} -
Thanks for the 3.X series of compilers. Good work!
@end itemize
