@node Where To Go From Here, Tips; Tricks and Warnings, Using the XSLT Support, Top
@chapter Where To Go From Here

Like most programming tasks, the best place to start is to just dive
in. The most obvious place to look is the xmlwrapp header files. They
are clean and well documented. When any document does not agree with
the header file, the header file will always win.

The header files are documented using the @uref{http://www.stack.nl/~dimitri/doxygen/,Doxygen}
syntax. The comments are then used to build the API reference
manual. This may be easier to read for some, although I still think
the header files are a better place to look.

@menu
* Getting Help::
@end menu

@node Getting Help, , , Where To Go From Here
@section Getting Help

If you need specific help using xmlwrapp, you can try the
@uref{http://pmade.org/mailman/listinfo/xmlwrapp-users,xmlwrapp users
and developers mailing list}.

To make sure you hear about the latest announcements pertaining to
xmlwrapp, you might want to also subscribe to the
@uref{http://pmade.org/mailman/listinfo/xmlwrapp-announce,announcements
mailing list}.

